namespace AuthService.Domain.Entities;

/// <summary>
/// Database entity representing a user account.
/// Password is stored as a hash via ICryptoManager — never plaintext.
/// </summary>
public class UserEntity
{
    public Guid Id { get; set; }

    public required string Username { get; set; }

    public required string Email { get; set; }

    public required string FirstName { get; set; }

    public required string LastName { get; set; }

    /// <summary>
    /// BCrypt (or other algorithm) hash of the user's password.
    /// Generated by ICryptoManager.HashPassword().
    /// </summary>
    public required string PasswordHash { get; set; }

    public bool IsActive { get; set; } = true;

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    // ── Navigation Properties ──
    public ICollection<UserRoleEntity> UserRoles { get; set; } = [];

    public ICollection<RefreshTokenEntity> RefreshTokens { get; set; } = [];
}

