/**
 * Car Custom Selectors
 *
 * Base selectors (selectCurrentDirection, selectSensorData)
 * are auto-generated by carFeature in car.reducer.ts.
 *
 * Add derived / composite selectors here when needed.
 */

import { createSelector } from '@ngrx/store';
import { carFeature } from '../reducers/car.reducer';

/**
 * Can we send direction commands?
 * True when a direction is set (not null).
 */
export const selectCanSendDirection = createSelector(
    carFeature.selectCurrentDirection,
    (direction) => direction !== null
);

/**
 * True when at least one sensor value is present.
 */
export const selectHasSensorData = createSelector(
    carFeature.selectSensorData,
    (data) => Object.values(data).some((v) => v !== undefined && v !== null)
);
