/**
 * Recording Custom Selectors
 *
 * Base selectors (selectRecordings, selectIsRecording, etc.)
 * are auto-generated by recordingFeature in recording.reducer.ts.
 *
 * Add derived / composite selectors here when needed.
 */

import { createSelector } from '@ngrx/store';
import { recordingFeature } from '../reducers/recording.reducer';

/**
 * True when the recordings list is non-empty.
 */
export const selectHasRecordings = createSelector(
    recordingFeature.selectRecordings,
    (recordings) => recordings.length > 0
);

/**
 * True when any recording operation is in progress (loading, recording, replaying).
 */
export const selectIsBusy = createSelector(
    recordingFeature.selectIsLoadingList,
    recordingFeature.selectIsRecording,
    recordingFeature.selectIsReplaying,
    (loading, recording, replaying) => loading || recording || replaying
);

