/**
 * Auth Custom Selectors
 * 
 * Contains derived/computed selectors that combine multiple pieces of auth state.
 * Base selectors (selectUser, selectToken, etc.) are auto-generated by authFeature.
 * 
 * Use this file for selectors that:
 * - Combine multiple state properties
 * - Contain complex business logic
 * - Need memoization for expensive calculations
 * 
 * DON'T add selectors for simple property access (use template: (user$ | async)?.name)
 */

import { createSelector } from '@ngrx/store';
import { authFeature } from '../reducers/auth.reducer';

/**
 * Derived selector: Is user currently logging in?
 * Combines: isLoading && !isAuthenticated
 * 
 * Use cases:
 * - Show loading spinner on login button
 * - Disable login form during authentication
 */
export const selectIsLoggingIn = createSelector(
  authFeature.selectIsLoading,
  authFeature.selectIsAuthenticated,
  (isLoading, isAuthenticated) => isLoading && !isAuthenticated
);

// Add more custom/derived selectors here as needed
// Examples:
// - selectCanAccessDashboard (combines user role + permissions)
// - selectAuthStatus (composite selector for guards)
// - selectTokenExpiry (calculates expiration from token)
