/**
 * Auth Custom Selectors
 * 
 * Contains derived/computed selectors that combine multiple pieces of auth state.
 * Base selectors (selectUser, selectToken, etc.) are auto-generated by authFeature.
 * 
 * Use this file for selectors that:
 * - Combine multiple state properties
 * - Contain complex business logic
 * - Need memoization for expensive calculations
 * 
 * DON'T add selectors for simple property access (use template: (user$ | async)?.name)
 */

import { createSelector } from '@ngrx/store';
import { authFeature } from '../reducers/auth.reducer';

/**
 * Derived selector: Is user currently logging in?
 * Combines: isLoading && !isAuthenticated
 * 
 * Use cases:
 * - Show loading spinner on login button
 * - Disable login form during authentication
 */
export const selectIsLoggingIn = createSelector(
  authFeature.selectIsLoading,
  authFeature.selectIsAuthenticated,
  (isLoading, isAuthenticated) => isLoading && !isAuthenticated
);

export const selectUserRoles = createSelector(
  authFeature.selectUser,
  (user) => user?.roles ?? []
);

export const selectIsAdmin = createSelector(
  selectUserRoles,
  (roles) => roles.includes('Admin')
);

export const selectIsOperator = createSelector(
  selectUserRoles,
  (roles) => roles.includes('Operator') || roles.includes('Admin')
);

export const selectIsViewer = createSelector(
  selectUserRoles,
  (roles) => roles.includes('Viewer')
);
